server:
  port: 8081

spring:
  data:
    mongodb:
      uri: ${AUTH_DB_URI:mongodb://localhost:27017/auth_db}
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: ${spring.application.name}

  prometheus:
    metrics:
      export:
        enabled: true