spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}

#Local fallback
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info


security:
  jwt:
   
    secret: ${JWT_SECRET}
    access-token-expiry-ms: ${JWT_ACCESS_EXPIRY_MS:900000}      # 15 minutes (PRD sec 6.8)
    refresh-token-expiry-ms: ${JWT_REFRESH_EXPIRY_MS:604800000} # 7 days     (PRD sec 6.8)


gateway:
  url: ${GATEWAY_URL:http://localhost:8080}
