spring:
  application:
    name: transaction-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}


server:
  port: 8085


security:
  internal:
    api-key: ${INTERNAL_API_KEY:f2d26f3cac654b94db725f955aba7a465bbd3fedd46996ae1e48be69b6893bfb}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
