server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          
          uri: ${CONFIG_REPO_URI:https://github.com/cupnoodles7/smart-banking-microservices.git}
          default-label: ${CONFIG_REPO_LABEL:main}
          search-paths: config-repo
          clone-on-start: true
          force-pull: true
          timeout: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
